"""Type stubs for dynamically generated HTML and SVG tag functions."""

from collections.abc import Callable, Iterator
from typing import Any

# ---------------------------------------------------------------------------
# Inline stub for fastcore.xml.FT (fastcore ships no py.typed / .pyi files).
# Defining the class here gives downstream users real attribute completion
# and type-checking on every tag function's return value.
# ---------------------------------------------------------------------------

class FT:
    tag: str
    children: tuple[Any, ...]
    attrs: dict[str, Any]
    void_: bool
    def __init__(
        self,
        tag: str,
        cs: tuple[Any, ...],
        attrs: dict[str, Any] | None = ...,
        void_: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    def on(self, f: Callable[..., Any]) -> None: ...
    def changed(self) -> FT: ...
    @property
    def list(self) -> list[Any]: ...
    def get(self, k: str, default: Any = ...) -> Any: ...
    def __setattr__(self, k: str, v: Any) -> None: ...
    def __getattr__(self, k: str) -> Any: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __getitem__(self, idx: int) -> Any: ...
    def __setitem__(self, i: int, o: Any) -> None: ...
    def __call__(self, *c: Any, **kw: Any) -> FT: ...
    def set(self, *c: Any, **kw: Any) -> FT: ...

__all__ = [
    "A",
    "Abbr",
    "Address",
    "Area",
    "Article",
    "Aside",
    "Audio",
    "B",
    "Base",
    "Bdi",
    "Bdo",
    "Blockquote",
    "Body",
    "Br",
    "Button",
    "Canvas",
    "Caption",
    "Cite",
    "Code",
    "Col",
    "Colgroup",
    "Data",
    "Datalist",
    "Dd",
    "Del",
    "Details",
    "Dfn",
    "Dialog",
    "Div",
    "Dl",
    "Dt",
    "Em",
    "Embed",
    "Fencedframe",
    "Fieldset",
    "Figcaption",
    "Figure",
    "Footer",
    "Form",
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "Head",
    "Header",
    "Hgroup",
    "Hr",
    "Html",
    "I",
    "Iframe",
    "Img",
    "Input",
    "Ins",
    "Kbd",
    "Label",
    "Legend",
    "Li",
    "Link",
    "Main",
    "Map",
    "Mark",
    "Menu",
    "Meta",
    "Meter",
    "Nav",
    "Noscript",
    "Object",
    "Ol",
    "Optgroup",
    "Option",
    "Output",
    "P",
    "Picture",
    "PortalExperimental",
    "Pre",
    "Progress",
    "Q",
    "Rp",
    "Rt",
    "Ruby",
    "S",
    "Samp",
    "Script",
    "Search",
    "Section",
    "Select",
    "Slot",
    "Small",
    "Source",
    "Span",
    "Strong",
    "Style",
    "Sub",
    "Summary",
    "Sup",
    "Table",
    "Tbody",
    "Td",
    "Template",
    "Textarea",
    "Tfoot",
    "Th",
    "Thead",
    "Time",
    "Title",
    "Tr",
    "Track",
    "U",
    "Ul",
    "Var",
    "Video",
    "Wbr",
    "Svg",
    "G",
    "Rect",
    "Circle",
    "Ellipse",
    "Line",
    "Polyline",
    "Polygon",
    "Text",
    "SvgPath",
    "AltGlyph",
    "AltGlyphDef",
    "AltGlyphItem",
    "Animate",
    "AnimateColor",
    "AnimateMotion",
    "AnimateTransform",
    "ClipPath",
    "Color_profile",
    "Cursor",
    "Defs",
    "Desc",
    "FeBlend",
    "FeColorMatrix",
    "FeComponentTransfer",
    "FeComposite",
    "FeConvolveMatrix",
    "FeDiffuseLighting",
    "FeDisplacementMap",
    "FeDistantLight",
    "FeFlood",
    "FeFuncA",
    "FeFuncB",
    "FeFuncG",
    "FeFuncR",
    "FeGaussianBlur",
    "FeImage",
    "FeMerge",
    "FeMergeNode",
    "FeMorphology",
    "FeOffset",
    "FePointLight",
    "FeSpecularLighting",
    "FeSpotLight",
    "FeTile",
    "FeTurbulence",
    "Filter",
    "Font",
    "Font_face",
    "Font_face_format",
    "Font_face_name",
    "Font_face_src",
    "Font_face_uri",
    "ForeignObject",
    "Glyph",
    "GlyphRef",
    "Hkern",
    "Image",
    "LinearGradient",
    "Marker",
    "Mask",
    "Metadata",
    "Missing_glyph",
    "Mpath",
    "Pattern",
    "RadialGradient",
    "Set",
    "Stop",
    "Switch",
    "Symbol",
    "TextPath",
    "Tref",
    "Tspan",
    "Use",
    "View",
    "Vkern",
    "ft_svg",
    "transformd",
    "SvgOob",
    "SvgInb",
    "PathFT",
]

# ---------------------------------------------------------------------------
# HTML tag functions (dynamically generated at runtime via globals())
# ---------------------------------------------------------------------------

def A(*c: Any, **kwargs: Any) -> FT: ...
def Abbr(*c: Any, **kwargs: Any) -> FT: ...
def Address(*c: Any, **kwargs: Any) -> FT: ...
def Area(*c: Any, **kwargs: Any) -> FT: ...
def Article(*c: Any, **kwargs: Any) -> FT: ...
def Aside(*c: Any, **kwargs: Any) -> FT: ...
def Audio(*c: Any, **kwargs: Any) -> FT: ...
def B(*c: Any, **kwargs: Any) -> FT: ...
def Base(*c: Any, **kwargs: Any) -> FT: ...
def Bdi(*c: Any, **kwargs: Any) -> FT: ...
def Bdo(*c: Any, **kwargs: Any) -> FT: ...
def Blockquote(*c: Any, **kwargs: Any) -> FT: ...
def Body(*c: Any, **kwargs: Any) -> FT: ...
def Br(*c: Any, **kwargs: Any) -> FT: ...
def Button(*c: Any, **kwargs: Any) -> FT: ...
def Canvas(*c: Any, **kwargs: Any) -> FT: ...
def Caption(*c: Any, **kwargs: Any) -> FT: ...
def Cite(*c: Any, **kwargs: Any) -> FT: ...
def Code(*c: Any, **kwargs: Any) -> FT: ...
def Col(*c: Any, **kwargs: Any) -> FT: ...
def Colgroup(*c: Any, **kwargs: Any) -> FT: ...
def Data(*c: Any, **kwargs: Any) -> FT: ...
def Datalist(*c: Any, **kwargs: Any) -> FT: ...
def Dd(*c: Any, **kwargs: Any) -> FT: ...
def Del(*c: Any, **kwargs: Any) -> FT: ...
def Details(*c: Any, **kwargs: Any) -> FT: ...
def Dfn(*c: Any, **kwargs: Any) -> FT: ...
def Dialog(*c: Any, **kwargs: Any) -> FT: ...
def Div(*c: Any, **kwargs: Any) -> FT: ...
def Dl(*c: Any, **kwargs: Any) -> FT: ...
def Dt(*c: Any, **kwargs: Any) -> FT: ...
def Em(*c: Any, **kwargs: Any) -> FT: ...
def Embed(*c: Any, **kwargs: Any) -> FT: ...
def Fencedframe(*c: Any, **kwargs: Any) -> FT: ...
def Fieldset(*c: Any, **kwargs: Any) -> FT: ...
def Figcaption(*c: Any, **kwargs: Any) -> FT: ...
def Figure(*c: Any, **kwargs: Any) -> FT: ...
def Footer(*c: Any, **kwargs: Any) -> FT: ...
def Form(*c: Any, **kwargs: Any) -> FT: ...
def H1(*c: Any, **kwargs: Any) -> FT: ...
def H2(*c: Any, **kwargs: Any) -> FT: ...
def H3(*c: Any, **kwargs: Any) -> FT: ...
def H4(*c: Any, **kwargs: Any) -> FT: ...
def H5(*c: Any, **kwargs: Any) -> FT: ...
def H6(*c: Any, **kwargs: Any) -> FT: ...
def Head(*c: Any, **kwargs: Any) -> FT: ...
def Header(*c: Any, **kwargs: Any) -> FT: ...
def Hgroup(*c: Any, **kwargs: Any) -> FT: ...
def Hr(*c: Any, **kwargs: Any) -> FT: ...
def Html(*c: Any, **kwargs: Any) -> FT: ...
def I(*c: Any, **kwargs: Any) -> FT: ...
def Iframe(*c: Any, **kwargs: Any) -> FT: ...
def Img(*c: Any, **kwargs: Any) -> FT: ...
def Input(*c: Any, **kwargs: Any) -> FT: ...
def Ins(*c: Any, **kwargs: Any) -> FT: ...
def Kbd(*c: Any, **kwargs: Any) -> FT: ...
def Label(*c: Any, **kwargs: Any) -> FT: ...
def Legend(*c: Any, **kwargs: Any) -> FT: ...
def Li(*c: Any, **kwargs: Any) -> FT: ...
def Link(*c: Any, **kwargs: Any) -> FT: ...
def Main(*c: Any, **kwargs: Any) -> FT: ...
def Map(*c: Any, **kwargs: Any) -> FT: ...
def Mark(*c: Any, **kwargs: Any) -> FT: ...
def Menu(*c: Any, **kwargs: Any) -> FT: ...
def Meta(*c: Any, **kwargs: Any) -> FT: ...
def Meter(*c: Any, **kwargs: Any) -> FT: ...
def Nav(*c: Any, **kwargs: Any) -> FT: ...
def Noscript(*c: Any, **kwargs: Any) -> FT: ...
def Object(*c: Any, **kwargs: Any) -> FT: ...
def Ol(*c: Any, **kwargs: Any) -> FT: ...
def Optgroup(*c: Any, **kwargs: Any) -> FT: ...
def Option(*c: Any, **kwargs: Any) -> FT: ...
def Output(*c: Any, **kwargs: Any) -> FT: ...
def P(*c: Any, **kwargs: Any) -> FT: ...
def Picture(*c: Any, **kwargs: Any) -> FT: ...
def PortalExperimental(*c: Any, **kwargs: Any) -> FT: ...
def Pre(*c: Any, **kwargs: Any) -> FT: ...
def Progress(*c: Any, **kwargs: Any) -> FT: ...
def Q(*c: Any, **kwargs: Any) -> FT: ...
def Rp(*c: Any, **kwargs: Any) -> FT: ...
def Rt(*c: Any, **kwargs: Any) -> FT: ...
def Ruby(*c: Any, **kwargs: Any) -> FT: ...
def S(*c: Any, **kwargs: Any) -> FT: ...
def Samp(*c: Any, **kwargs: Any) -> FT: ...
def Script(*c: Any, **kwargs: Any) -> FT: ...
def Search(*c: Any, **kwargs: Any) -> FT: ...
def Section(*c: Any, **kwargs: Any) -> FT: ...
def Select(*c: Any, **kwargs: Any) -> FT: ...
def Slot(*c: Any, **kwargs: Any) -> FT: ...
def Small(*c: Any, **kwargs: Any) -> FT: ...
def Source(*c: Any, **kwargs: Any) -> FT: ...
def Span(*c: Any, **kwargs: Any) -> FT: ...
def Strong(*c: Any, **kwargs: Any) -> FT: ...
def Style(*c: Any, **kwargs: Any) -> FT: ...
def Sub(*c: Any, **kwargs: Any) -> FT: ...
def Summary(*c: Any, **kwargs: Any) -> FT: ...
def Sup(*c: Any, **kwargs: Any) -> FT: ...
def Table(*c: Any, **kwargs: Any) -> FT: ...
def Tbody(*c: Any, **kwargs: Any) -> FT: ...
def Td(*c: Any, **kwargs: Any) -> FT: ...
def Template(*c: Any, **kwargs: Any) -> FT: ...
def Textarea(*c: Any, **kwargs: Any) -> FT: ...
def Tfoot(*c: Any, **kwargs: Any) -> FT: ...
def Th(*c: Any, **kwargs: Any) -> FT: ...
def Thead(*c: Any, **kwargs: Any) -> FT: ...
def Time(*c: Any, **kwargs: Any) -> FT: ...
def Title(*c: Any, **kwargs: Any) -> FT: ...
def Tr(*c: Any, **kwargs: Any) -> FT: ...
def Track(*c: Any, **kwargs: Any) -> FT: ...
def U(*c: Any, **kwargs: Any) -> FT: ...
def Ul(*c: Any, **kwargs: Any) -> FT: ...
def Var(*c: Any, **kwargs: Any) -> FT: ...
def Video(*c: Any, **kwargs: Any) -> FT: ...
def Wbr(*c: Any, **kwargs: Any) -> FT: ...

# ---------------------------------------------------------------------------
# SVG tag functions (dynamically generated, except those with explicit defs)
# ---------------------------------------------------------------------------

def G(*c: Any, **kwargs: Any) -> FT: ...
def AltGlyph(*c: Any, **kwargs: Any) -> FT: ...
def AltGlyphDef(*c: Any, **kwargs: Any) -> FT: ...
def AltGlyphItem(*c: Any, **kwargs: Any) -> FT: ...
def Animate(*c: Any, **kwargs: Any) -> FT: ...
def AnimateColor(*c: Any, **kwargs: Any) -> FT: ...
def AnimateMotion(*c: Any, **kwargs: Any) -> FT: ...
def AnimateTransform(*c: Any, **kwargs: Any) -> FT: ...
def ClipPath(*c: Any, **kwargs: Any) -> FT: ...
def Color_profile(*c: Any, **kwargs: Any) -> FT: ...
def Cursor(*c: Any, **kwargs: Any) -> FT: ...
def Defs(*c: Any, **kwargs: Any) -> FT: ...
def Desc(*c: Any, **kwargs: Any) -> FT: ...
def FeBlend(*c: Any, **kwargs: Any) -> FT: ...
def FeColorMatrix(*c: Any, **kwargs: Any) -> FT: ...
def FeComponentTransfer(*c: Any, **kwargs: Any) -> FT: ...
def FeComposite(*c: Any, **kwargs: Any) -> FT: ...
def FeConvolveMatrix(*c: Any, **kwargs: Any) -> FT: ...
def FeDiffuseLighting(*c: Any, **kwargs: Any) -> FT: ...
def FeDisplacementMap(*c: Any, **kwargs: Any) -> FT: ...
def FeDistantLight(*c: Any, **kwargs: Any) -> FT: ...
def FeFlood(*c: Any, **kwargs: Any) -> FT: ...
def FeFuncA(*c: Any, **kwargs: Any) -> FT: ...
def FeFuncB(*c: Any, **kwargs: Any) -> FT: ...
def FeFuncG(*c: Any, **kwargs: Any) -> FT: ...
def FeFuncR(*c: Any, **kwargs: Any) -> FT: ...
def FeGaussianBlur(*c: Any, **kwargs: Any) -> FT: ...
def FeImage(*c: Any, **kwargs: Any) -> FT: ...
def FeMerge(*c: Any, **kwargs: Any) -> FT: ...
def FeMergeNode(*c: Any, **kwargs: Any) -> FT: ...
def FeMorphology(*c: Any, **kwargs: Any) -> FT: ...
def FeOffset(*c: Any, **kwargs: Any) -> FT: ...
def FePointLight(*c: Any, **kwargs: Any) -> FT: ...
def FeSpecularLighting(*c: Any, **kwargs: Any) -> FT: ...
def FeSpotLight(*c: Any, **kwargs: Any) -> FT: ...
def FeTile(*c: Any, **kwargs: Any) -> FT: ...
def FeTurbulence(*c: Any, **kwargs: Any) -> FT: ...
def Filter(*c: Any, **kwargs: Any) -> FT: ...
def Font(*c: Any, **kwargs: Any) -> FT: ...
def Font_face(*c: Any, **kwargs: Any) -> FT: ...
def Font_face_format(*c: Any, **kwargs: Any) -> FT: ...
def Font_face_name(*c: Any, **kwargs: Any) -> FT: ...
def Font_face_src(*c: Any, **kwargs: Any) -> FT: ...
def Font_face_uri(*c: Any, **kwargs: Any) -> FT: ...
def ForeignObject(*c: Any, **kwargs: Any) -> FT: ...
def Glyph(*c: Any, **kwargs: Any) -> FT: ...
def GlyphRef(*c: Any, **kwargs: Any) -> FT: ...
def Hkern(*c: Any, **kwargs: Any) -> FT: ...
def Image(*c: Any, **kwargs: Any) -> FT: ...
def LinearGradient(*c: Any, **kwargs: Any) -> FT: ...
def Marker(*c: Any, **kwargs: Any) -> FT: ...
def Mask(*c: Any, **kwargs: Any) -> FT: ...
def Metadata(*c: Any, **kwargs: Any) -> FT: ...
def Missing_glyph(*c: Any, **kwargs: Any) -> FT: ...
def Mpath(*c: Any, **kwargs: Any) -> FT: ...
def Pattern(*c: Any, **kwargs: Any) -> FT: ...
def RadialGradient(*c: Any, **kwargs: Any) -> FT: ...
def Set(*c: Any, **kwargs: Any) -> FT: ...
def Stop(*c: Any, **kwargs: Any) -> FT: ...
def Switch(*c: Any, **kwargs: Any) -> FT: ...
def Symbol(*c: Any, **kwargs: Any) -> FT: ...
def TextPath(*c: Any, **kwargs: Any) -> FT: ...
def Tref(*c: Any, **kwargs: Any) -> FT: ...
def Tspan(*c: Any, **kwargs: Any) -> FT: ...
def Use(*c: Any, **kwargs: Any) -> FT: ...
def View(*c: Any, **kwargs: Any) -> FT: ...
def Vkern(*c: Any, **kwargs: Any) -> FT: ...

# ---------------------------------------------------------------------------
# Explicitly defined SVG functions (with richer signatures)
# ---------------------------------------------------------------------------

def ft_svg(
    tag: str,
    *c: Any,
    transform: str | None = ...,
    opacity: int | float | str | None = ...,
    clip: str | None = ...,
    mask: str | None = ...,
    filter: str | None = ...,
    vector_effect: str | None = ...,
    pointer_events: str | None = ...,
    **kwargs: Any,
) -> FT: ...
def Svg(
    *args: Any,
    viewBox: str | None = ...,
    h: int | str | None = ...,
    w: int | str | None = ...,
    height: int | str | None = ...,
    width: int | str | None = ...,
    xmlns: str = ...,
    **kwargs: Any,
) -> FT: ...
def Rect(
    width: Any,
    height: Any,
    x: Any = ...,
    y: Any = ...,
    fill: Any = ...,
    stroke: Any = ...,
    stroke_width: Any = ...,
    rx: Any = ...,
    ry: Any = ...,
    **kwargs: Any,
) -> FT: ...
def Circle(
    r: Any,
    cx: Any = ...,
    cy: Any = ...,
    fill: Any = ...,
    stroke: Any = ...,
    stroke_width: Any = ...,
    **kwargs: Any,
) -> FT: ...
def Ellipse(
    rx: Any,
    ry: Any,
    cx: Any = ...,
    cy: Any = ...,
    fill: Any = ...,
    stroke: Any = ...,
    stroke_width: Any = ...,
    **kwargs: Any,
) -> FT: ...
def Line(
    x1: Any,
    y1: Any,
    x2: Any = ...,
    y2: Any = ...,
    stroke: Any = ...,
    w: Any = ...,
    stroke_width: Any = ...,
    **kwargs: Any,
) -> FT: ...
def Polyline(
    *args: Any,
    points: Any = ...,
    fill: Any = ...,
    stroke: Any = ...,
    stroke_width: Any = ...,
    **kwargs: Any,
) -> FT: ...
def Polygon(
    *args: Any,
    points: Any = ...,
    fill: Any = ...,
    stroke: Any = ...,
    stroke_width: Any = ...,
    **kwargs: Any,
) -> FT: ...
def Text(
    *args: Any,
    x: Any = ...,
    y: Any = ...,
    font_family: Any = ...,
    font_size: Any = ...,
    fill: Any = ...,
    text_anchor: Any = ...,
    dominant_baseline: Any = ...,
    font_weight: Any = ...,
    font_style: Any = ...,
    text_decoration: Any = ...,
    **kwargs: Any,
) -> FT: ...
def transformd(
    translate: tuple[Any, ...] | None = ...,
    scale: tuple[Any, ...] | None = ...,
    rotate: tuple[Any, ...] | None = ...,
    skewX: int | float | None = ...,
    skewY: int | float | None = ...,
    matrix: tuple[Any, ...] | None = ...,
) -> dict[str, str]: ...

class PathFT(FT):
    def M(self, x: int | float, y: int | float) -> PathFT: ...
    def L(self, x: int | float, y: int | float) -> PathFT: ...
    def H(self, x: int | float) -> PathFT: ...
    def V(self, y: int | float) -> PathFT: ...
    def C(
        self, x1: int | float, y1: int | float, x2: int | float, y2: int | float, x: int | float, y: int | float
    ) -> PathFT: ...
    def S(self, x2: int | float, y2: int | float, x: int | float, y: int | float) -> PathFT: ...
    def Q(self, x1: int | float, y1: int | float, x: int | float, y: int | float) -> PathFT: ...
    def T(self, x: int | float, y: int | float) -> PathFT: ...
    def A(
        self,
        rx: int | float,
        ry: int | float,
        x_axis_rotation: int | float,
        large_arc_flag: int,
        sweep_flag: int,
        x: int | float,
        y: int | float,
    ) -> PathFT: ...
    def Z(self) -> PathFT: ...
    def m(self, dx: int | float, dy: int | float) -> PathFT: ...
    def l(self, dx: int | float, dy: int | float) -> PathFT: ...
    def h(self, dx: int | float) -> PathFT: ...
    def v(self, dy: int | float) -> PathFT: ...
    def c(
        self, dx1: int | float, dy1: int | float, dx2: int | float, dy2: int | float, dx: int | float, dy: int | float
    ) -> PathFT: ...
    def s(self, dx2: int | float, dy2: int | float, dx: int | float, dy: int | float) -> PathFT: ...
    def q(self, dx1: int | float, dy1: int | float, dx: int | float, dy: int | float) -> PathFT: ...
    def t(self, dx: int | float, dy: int | float) -> PathFT: ...
    def a(
        self,
        rx: int | float,
        ry: int | float,
        x_axis_rotation: int | float,
        large_arc_flag: int,
        sweep_flag: int,
        dx: int | float,
        dy: int | float,
    ) -> PathFT: ...
    def z(self) -> PathFT: ...

def SvgPath(
    d: str = ...,
    fill: Any = ...,
    stroke: Any = ...,
    stroke_width: Any = ...,
    **kwargs: Any,
) -> PathFT: ...
def SvgOob(*args: Any, **kwargs: Any) -> FT: ...
def SvgInb(*args: Any, **kwargs: Any) -> FT: ...
def __getattr__(tag: str) -> Callable[..., FT]: ...
